name: Waka Readme

on:
  schedule:
    # Atualiza todo dia às 15:30 (horário de Brasília)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_LOC_CHART: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_UPDATED_DATE: "true"
          SHOW_SHORT_INFO: "false"
          COMMIT_MESSAGE: "chore: update WakaTime stats"
